CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS cal_tracker_dev AUTHORIZATION cal_tracker;
CREATE SCHEMA IF NOT EXISTS cal_tracker_pro AUTHORIZATION cal_tracker;

GRANT USAGE, CREATE ON SCHEMA cal_tracker_dev TO cal_tracker;
GRANT USAGE, CREATE ON SCHEMA cal_tracker_pro TO cal_tracker;

ALTER DEFAULT PRIVILEGES FOR USER cal_tracker IN SCHEMA cal_tracker_dev
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cal_tracker;
ALTER DEFAULT PRIVILEGES FOR USER cal_tracker IN SCHEMA cal_tracker_pro
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cal_tracker;

ALTER DEFAULT PRIVILEGES FOR USER cal_tracker IN SCHEMA cal_tracker_dev
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO cal_tracker;
ALTER DEFAULT PRIVILEGES FOR USER cal_tracker IN SCHEMA cal_tracker_pro
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO cal_tracker;
